import { getListOfCategory } from "@/api/category";
import { getProductsBySort } from "@/api/products";
import Banner from "@/components/Home/Banner/Banner";
import BestSellers from "@/components/Home/BestSellers/BestSellers";
import Categories from "@/components/Home/SubCategories/SubCategories";
import NewArrivals from "@/components/Home/NewArrivals/NewArrivals";
import Services from "@/components/Home/Services/Services";
import MainLayout from "@/layouts/MainLayout/MainLayout";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { IProduct } from "./../../types/product.type";
import { getAllSubCategories } from "@/api/sub-categories";

type PropsType = {
    products: IProduct[];
    bestSellerProducts: IProduct[];
    subCategories: any;
};

export default function Home({
    products,
    bestSellerProducts,
    subCategories,
}: PropsType) {
    return (
        <>
            <Head>
                <title>Aladin-Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <Banner />
                <Services />
                <Categories subCategories={subCategories} />
                <NewArrivals products={products} />
                <BestSellers products={bestSellerProducts} />
            </MainLayout>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async () => {
    const { data } = await getProductsBySort("createdAt", "desc");
    const { data: bestSellerProductData } = await getProductsBySort(
        "sold",
        "desc"
    );
    const { data: subCategoriesData } = await getAllSubCategories();
    return {
        props: {
            products: data,
            bestSellerProducts: bestSellerProductData,
            subCategories: subCategoriesData,
        },
    };
};
