import NewArrivals from "@/components/Home/NewArrivals/NewArrivals";
import MainLayout from "@/layouts/MainLayout/MainLayout";
import Head from "next/head";
import Banner from "../components/Home/Banner/Banner";

export default function Home() {
    return (
        <>
            <Head>
                <title>Aladin-Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <Banner />
                <NewArrivals/>
            </MainLayout>
        </>
    );
}
